title: MNNIT Computer Coding Club
description: The GitHub pages home to MNNIT Computer Coding Club
image: sample_image.png
type: website
author: computer.club@mnnit.ac.in
favicon: "./cclogo_favicon.jpeg"
url: https://cc-mnnit.github.io
